### ISSUE TITLE
Add Support to Wagtail 5.2

### ISSUE THREAD

**Issue by aliceni81** [jazzband/wagtailmenus#464] opened 2023-11-06 08:41 UTC
When I upgrade wagtail version from 5.1.3 to 5.2, I got the following the warnings:
wagtailmenus.FlatMenu: (wagtailadmin.W002) FlatMenu.content_panels will have no effect on modeladmin editing
        HINT: Ensure that FlatMenu uses `panels` instead of `content_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Content tab for the content_panels to render in.
wagtailmenus.FlatMenu: (wagtailadmin.W002) FlatMenu.settings_panels will have no effect on modeladmin editing
        HINT: Ensure that FlatMenu uses `panels` instead of `settings_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Settings tab for the settings_panels to render in.
wagtailmenus.MainMenu: (wagtailadmin.W002) MainMenu.content_panels will have no effect on modeladmin editing
        HINT: Ensure that MainMenu uses `panels` instead of `content_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Content tab for the content_panels to render in.
wagtailmenus.MainMenu: (wagtailadmin.W002) MainMenu.settings_panels will have no effect on modeladmin editing
        HINT: Ensure that MainMenu uses `panels` instead of `settings_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Settings tab for the settings_panels to render in.

Wagtail version: 5.2
Wagtailmenu version: 3.1.9

**Comment by ababic** [comment] 2023-11-11 20:39
This warning can be safely ignored. The add/edit views for wagtailmenus use [this mixin](https://github.com/jazzband/wagtailmenus/blob/v3.1.9/wagtailmenus/views.py#L47-L67), which takes care of creating an edit handler for the view to use.

**Comment by MrCordeiro** [comment] 2023-11-11 22:22
@ababic , do you think it makes sense filter out these specific warnings with `warnings.filterwarnings` + an explanatory comment?

**Comment by ababic** [comment] 2023-11-12 06:34
@MrCordeiro if trivial, then sure. I can't say I'm very familiar with that API though. It looks a little cumbersome.

**Comment by MrCordeiro** [comment] 2023-12-04 17:09
Just a small update on that item.

The warnings come from Django's system checks framework. The problem is that a third-party app can't directly manipulate checks registered by other apps (Wagtail, in this case).

The workaround is having developers silence these warnings in their applications, using the `SILENCED_SYSTEM_CHECKS` settings:

```python
# settings.py
SILENCED_SYSTEM_CHECKS = ["wagtailadmin.W002"]
```

The problem with this, of course, is that it will also silence any instance where the warning _shouldn't_ be ignored. **So I don't recommend it**.

--- 

I'm going to close this issue for now.

I'm also leaving a copy of @ababic's answer to #468 so that visitors can quickly find the reason why they can safely ignore those warnings:

>  Hi @yarickprih. These changes aren't actually needed, because the [custom views](https://github.com/jazzband/wagtailmenus/blob/v3.1.9/wagtailmenus/views.py) used by wagtailmenus [generate their own edit handler](https://github.com/jazzband/wagtailmenus/blob/v3.1.9/wagtailmenus/views.py#L49-L60) from the `content_panels` and `settings_panels` attributes on the model. 
>
> Adding these `edit_handler` attributes to the models actually means that, in order to add their own panels to either tab, developers need to completely override `edit_handler` instead of just adding items to `content_panels` and `settings_panels` (like they can currently).
>
> _Originally posted by @ababic in https://github.com/jazzband/wagtailmenus/issues/468#issuecomment-1806913973_

**Closed** 2023-12-04 17:10 UTC
